name: CI - Huella Hídrica (Quality & Testing)

on:
  push:
    branches:
      - '**' # Ejecutar en CUALQUIER rama 
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  # ======================================================
  # Job 1: CI (Calidad de Código y Tests)
  # ======================================================
  ci:
    name: Code Quality and Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Usamos 3.10 para coincidir con los servidores Ubuntu en AWS
      - name: Set up Python 3.10
        uses: actions/setup-python@v5 
        with:
          python-version: "3.10"
          
      - name: Install dependencies and Quality Tools
        run: |
          python -m pip install --upgrade pip
          # Instalamos las 3 herramientas clave + pytest
          pip install flake8 pytest black isort
          # Si existe requirements.txt, lo instala. Si no, sigue.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # --- Auditoría de Calidad (Quality Gate) ---
      
      # 1. Black: Verifica el formato visual
      - name: Check Code Formatting (Black)
        run: |
          black --check .
          
      # 2. Isort: Verifica el orden de los imports
      - name: Check Import Sorting (isort)
        run: |
          isort --check-only .
          
      # 3. Flake8: Verifica errores de sintaxis y linter
      - name: Lint with flake8
        run: |
          # Errores graves (detienen el pipeline)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Advertencias de estilo (no detienen el pipeline gracias a --exit-zero)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      # --- Pruebas Automatizadas ---
      - name: Test with pytest
        run: |
          # Busca y ejecuta cualquier test que exista en la carpeta
          pytest

  # ======================================================
  # Job 2: CD (Despliegue Continuo) - OPCIONAL
  # Descomentar solo si ya configuraron los Secrets en GitHub
  # ======================================================
  # deploy:
  #   name: Continuous Deployment to S3
  #   runs-on: ubuntu-latest
  #   needs: [ci] 
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-2
  #         
  #     - name: Deploy to S3
  #       run: |
  #         # Ejemplo: Subir la carpeta src al bucket
  #         aws s3 sync ./src s3://henry-pf-g2-huella-hidrica-dev-ale/scripts/ \
  #           --delete
  #         echo "Despliegue completado."