name: CI - Validación Continua (Python & Docker)

# 1. EL ARREGLO PARA CARLOS:
# Esto correrá en CUALQUIER rama (*), no solo en main.
# También corre automáticamente cuando alguien abre un Pull Request.
on:
  push:
    branches: [ "**" ]      # "**" significa "todas las ramas existentes"
  pull_request:
    branches: [ "**" ]      # Valida también los intentos de fusión

jobs:
  build-and-test:
    name: Validar Código y Tests
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Bajar el código del repo
    - name: Checkout del código
      uses: actions/checkout@v3

    # Paso 2: Preparar Python (ajusta la versión si usan otra)
    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Paso 3: Instalar dependencias
    # Busca si existe requirements.txt, si no, no falla.
    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest # Instalamos linter y test runner

    # Paso 4: Linting (Calidad de código)
    # Esto revisa sintaxis en TODAS las carpetas automáticamente.
    # --count --select... son configuraciones estándar para detectar errores graves.
    - name: Analizar código con Flake8 (Linter)
      run: |
        # detiene el build si hay errores de sintaxis o nombres indefinidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero trata todos los errores como advertencias (opcional)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Paso 5: Correr Tests Automatizados
    # Busca archivos test_*.py en CUALQUIER carpeta automáticamente.
    - name: Ejecutar Tests con Pytest
      run: |
        pytest

    # Paso 6: (Opcional) Verificar que Docker construye bien
    # Si tienen un Dockerfile, esto prueba que la imagen se pueda crear sin errores.
    - name: Verificar Build de Docker
      if: hashFiles('Dockerfile') != '' # Solo corre si existe un Dockerfile
      run: docker build . --file Dockerfile --tag mi-proyecto-test:latest